name: compliance-checker-issue-310
channels:
- conda-forge
- axiom-data-science
- kwilcox
- defaults
dependencies:
- conda-forge::ca-certificates=2016.8.31=0
- conda-forge::cc-plugin-glider=1.0.2=py35_0
- conda-forge::certifi=2016.8.31=py35_0
- conda-forge::cf_units=1.1.2=py35_0
- conda-forge::compliance-checker=2.2.1=py35_0
- conda-forge::curl=7.49.1=1
- conda-forge::expat=2.1.0=2
- conda-forge::hdf4=4.2.12=0
- conda-forge::hdf5=1.8.17=4
- conda-forge::icu=56.1=4
- conda-forge::isodate=0.5.4=py35_0
- conda-forge::jinja2=2.8=py35_1
- conda-forge::jpeg=9b=0
- conda-forge::libiconv=1.14=3
- conda-forge::libnetcdf=4.4.1=0
- conda-forge::libxml2=2.9.4=0
- conda-forge::libxslt=1.1.29=1
- conda-forge::lxml=3.6.4=py35_0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::ncurses=5.9=9
- conda-forge::netcdf4=1.2.4=np111py35_2
- conda-forge::openssl=1.0.2h=2
- conda-forge::owslib=0.12.0=py35_0
- conda-forge::pip=8.1.2=py35_0
- conda-forge::pygeoif=0.6=py35_1
- conda-forge::pyproj=1.9.5.1=py35_0
- conda-forge::python=3.5.2=2
- conda-forge::python-dateutil=2.5.3=py35_0
- conda-forge::pytz=2016.6.1=py35_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.11.1=py35_0
- conda-forge::setuptools=26.1.1=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=0
- conda-forge::udunits2=2.2.20=1
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.8=3
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- pip:
  - cc-plugin-glider==1.0.2
  - certifi==2016.8.31
  - cf-units==1.1.2
  - compliance-checker==2.2.1
  - isodate==0.5.4
  - jinja2==2.8
  - lxml==3.6.4
  - markupsafe==0.23
  - netcdf4==1.2.4
  - owslib==0.12.0
  - pip==8.1.2
  - pygeoif==0.6
  - pyproj==1.9.5.1
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - requests==2.11.1
  - setuptools==26.1.1.post20160901
  - six==1.10.0
  - wheel==0.29.0
